version: "1"

tools:
  code_review:
    enabled: true
    style_guide: .gemini/styleguide.md
    # 파일 확장자별로 리뷰 룰을 다르게 적용할 수 있습니다.
    # 추후 Gemini Code Assist가 제공하는 여러 툴을 설정할 수 있습니다.

# 리뷰를 무시할 파일 또는 디렉터리 설정
exclude:
  # 백엔드
  - "**/*.class"
  - "build/"
  - "target/"
  - ".gradle/"
  - "out/"
